name: docker image build and push
on: [push]
jobs:
    Docker-Build-Push:
        runs-on: ubuntu-latest
        steps:
            -
                name: checkout
                uses: actions/checkout@v2
            -
                name: set up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: set up docker buildx
                id: buildx
                uses: docker/setup-buildx-action@v1
            -
                name: login to Dockerhub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USER }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -
                name: build push
                id: docker_build
                uses: docker/build-push-action@v2
                with:
                    push: true
                    platforms: linux/amd64,linux/arm64
                    tags: lnmp:latest
