name: docker image build and push
on: [push]
jobs:
	Docker-Build-Push:
		runs-on:centos-latest
		steps:
			-
				name: checkout
				uses: actions/checkout@v2
			-
				name: set up QEMU
				uses: docker/setup-qemu-action@v1
			-
				name: set up docker buildx
				id: buildx
				uses: docker/setup-buildx-action@v1
			-
				name: Available platforms
				run: echo ${{ step.buildx.outpus.platforms }}
			-
				name: docker login build push
				run: /
					docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
					docker buildx ls
					docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t lnmp:latest .
